<?php include('includes/header.php')?>
<style>
    .page-title h1{
        font-size: 21px;
      text-align: center;
      margin-bottom:10px;
    }
    .custum-content h2{
        font-size: 18px;
    }
     p, span,ol,ul,li{
        color:#666 !important;
    }
</style>
<section class="ptb-50 bg-dark" style="padding-top:50px;">
    <div class="container custum-content">
        <br><br>
                 <div class="page-title">
                    <h1> LEGAL </h1>
                </div>
                <div class="card border-0 shadow-sm">
                    <div class="card-body">
                        <h2>TERMS &amp; CONDITION</h2>

                        

                        <p>This document is an electronic record in terms of Information Technology Act, 2000 and rules
                            there under as applicable and the amended provisions pertaining to electronic records in
                            various statutes as amended by the Information Technology Act, 2000. This electronic record
                            is generated by a computer system and does not require any physical or digital signatures.
                        </p>

                        <p>This document is published in accordance with the provisions of Rule 3 (1) of the Information
                            Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and
                            regulations, privacy policy and Terms of Use for access or usage of domain name
                            [www.arteno.in][www.arteno.in] (&ldquo;Website&rdquo;), including the related mobile site
                            and mobile application (hereinafter referred to as &ldquo;Platform&rdquo;)</p>

                        <p>Membership Eligibility</p>

                        <p>Transaction on the Platform is available only to persons who can form legally binding
                            contracts under Indian Contract Act, 1872. Persons who are &quot;incompetent to
                            contract&quot; within the meaning of the Indian Contract Act, 1872 including un-discharged
                            insolvents etc. are not eligible to use the Platform. If you are a minor i.e. under the age
                            of 18 years, you may use the Platform or access content on the Platform only under the
                            supervision and prior consent/ permission of a parent ormlegal guardian.</p>

                        

                        <h2>RETURN POLICY</h2>

                        

                        <p>Returns is a scheme provided by respective sellers directly under this policy in terms of
                            which the option of exchange, replacement and/ or refund is offered by the respective
                            sellers to you. All products listed under a particular category may not have the same
                            returns policy. For all products, the returns/replacement policy provided on the product
                            page shall prevail over the general returns policy.</p>

                        

                        <h2>PAYMENT SECURITY</h2>

                        

                        <p>Your online transaction on Arteno is secure with the highest levels of transaction security
                            currently available on the Internet. Arteno uses 256-bit encryption technology to protect
                            your card information while securely transmitting it to the respective banks for payment
                            processing. All credit card and debit card payments on Arteno are processed through secure
                            and trusted payment gateways managed by leading banks. Banks now use the 3D Secure password
                            service for online transactions, providing an additional layer of security through identity
                            verification.</p>

                        <h2>DISCLAIMER</h2>

                        

                        <p>Any damage or loss to the product after delivery will not be covered under this program and
                            will completely be the Buyer&#39;s responsibility. Buyers should refuse to accept delivery
                            if the item is damaged.</p>

                    </div>
                </div>
 </div>
</section>
<br> <br>
<?php include('includes/footer.php')?>